fixed init func

diff --git a/box/box b/box/box
--- a/box/box
+++ b/box/box
@@ -4,7 +4,7 @@ ARCH=x32
 DEV=/dev/sdc
 USER=`whoami`
 PASSWD=kali
-BOX_DIR=/media/`whoami`/box
+BOX_DIR=/media/$USER/box
 
 BOX_DEVPART="$DEV"3
 BOX_HOME=$BOX_DIR/home
@@ -51,12 +51,9 @@ box_usage()
 	echo "Usage: box [option]"
 	echo "Options:"
 	echo " -i                    init box environment"
-	echo " -s                    set box environment extensions"
-	echo " -c                    clean machine RAM"
-	echo " -d                    debug box to improve it"
-	echo " -H                    wrapper for command shutdown"
-	echo " -p                    download, compile and install user packages"
-	echo " -u                    user utils: conn, send"
+	echo " -s                    set box environment"
+	echo " -c                    free box RAM memory"
+	echo " -u                    user utils: conn, send, pkgs, halt"
 	echo " -h                    give this help list"
 	echo " -v                    show box version"
 }
@@ -64,22 +61,32 @@ box_usage()
 
 box_init()
 {
-	printf "Device (default /dev/sdc): "   && read _DEV
-	test -z $_DEV || DEV=$_DEV
-	test -e $DEV  || (echo -e "\nError: no such disk device \`$DEV'" && exit)
-
 	echo "[*] init disk partition"
-	printf "[!] Do you want to format \`box\` disk partition? [y/N] " && read anw
-	test $anw = yes || (echo "Abort" && exit)
+	printf "  Device (default /dev/sdc): "   && read _DEV
+	
+	test -z $_DEV || DEV=$_DEV && test -b $DEV # && echo "OK $DEV" || echo "ERR $DEV"
 
-	test -e $BOX_DIR
-	if [[ $? -eq 0 ]]; then
-		echo   "[~] Warning: \`box\` partitioin exists already"
-		printf "[!] Do you want to format  \`box\` partitioin anyway? [y/N] " && read anw
-		test $anw = yes && echo "    [-] Formating disk partitioin" || (echo "Abort" && exit)
+	if [[ $? -eq 1 ]]; then
+		echo -e "  Error: no such disk device \`$DEV'"
+		exit
 	fi
 
-	echo "    [-] make partitioin"
+	printf "  Do you want to format \`box\` disk partition? [y/N] " && read anw
+	if [[ $anw != 'yes' ]]; then
+		echo "Abort" && exit
+	fi
+
+	if [[ -d $BOX_DIR ]]; then
+		echo "  Warning: \`box\` partitioin exists already."
+		printf "  Do you want to format \`box\` partitioin anyway? [y/N] " && read anw
+		if [[ $anw != 'yes' ]]; then
+			echo "Abort"
+			exit
+		fi
+		echo -e "\n  Format disk partitioin"
+	fi
+
+	echo "  Make disk partitioin"
 	sudo wipefs --all --force $BOX_DEVPART
 	echo -e 'n\n \n \n \n \n p\n w\n' | sudo fdisk $DEV
 	sudo mkfs.ext4 $BOX_DEVPART
@@ -89,11 +96,11 @@ box_init()
 	sudo chown $USER:$USER -R $BOX_DIR
 	rm -rf $BOX_DIR/*
 
-	echo "    [-] make system directories"
+	echo "  Make system directories"
 	for item in ${BOX_ROOT[@]}; do
 		mkdir -p $item;
 	done
-	echo "    [-] make user directories"
+	echo "  Make user directories"
 	for item in ${BOX_DIRS[@]}; do
 		echo "$item"
 		mkdir -p $item;
@@ -110,15 +117,14 @@ box_init()
 
 _save_new_passwd()
 {
-	echo "    [-] save new password"
 	printf "Default password: "            && read _DEF_PASSWD
 	printf "New password: "                && read _NEW_PASSWD
-	if [[ $_DEF_PASSWD != '' ]]; then
-		printf "$_DEF_PASSWD"":" > $BOX_HOME/.box-credentials
+
+	if [[ $_DEF_PASSWD == '' || $_NEW_PASSWD == '' ]]; then
+		echo -e "Error: password is empty\n"
+		_save_new_passwd
 	fi
-	if [[ $_NEW_PASSWD != '' ]]; then
-		echo $_NEW_PASSWD >> $BOX_HOME/.box-credentials
-	fi
+	echo "$_DEF_PASSWD:$_NEW_PASSWD" > $BOX_HOME/.box-credentials
 }
 _save_git_credentials()
 {
@@ -262,9 +268,15 @@ _user_utils()
 				echo "scp: cannot access '$filepath': No such file or directory" && exit
 			fi
 			;;
+		pkgs )
+			_pkgs
+			;;
+		halt )
+			sudo shutdown now
+			;;
 	esac
+	#unset $NAME, $IP, $PASSWD, $DIR
 }
-
 
 
 box_clean()
@@ -278,21 +290,8 @@ box_clean()
 }
 
 
-box_debug()
-{
-	echo "[*] debug box"
-}
-
-
-box_halt()
-{
-	echo '[*] halt machine'
-	sudo shutdown now
-}
-
-
 # Interface
-while getopts ":isc:Hhdpu:v" opt; do
+while getopts ":isc:hu:v" opt; do
 	case ${opt} in
 		i)
 			box_init ;;
@@ -300,20 +299,14 @@ while getopts ":isc:Hhdpu:v" opt; do
 			box_set ;;
 		c)
 			box_clean $OPTARG ;;
-		d)
-			box_debug ;;
-		H)
-			box_halt ;;
 		h)
 			box_usage ;;
-		p)
-			_pkgs ;;
 		u)
 			_user_utils $OPTARG ;;
 		v)
 			echo "box (particle) $VERSION" ;;
 		:)
-			echo "Option -$OPTARG requires argument" ;;
+			echo "Option -$OPTARG requires argument. Use option \`-h' for more information" ;;
 	   \?)
 			echo "Unknown option character \`-$OPTARG'" ;;
 	esac
